# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RectangleArea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ShapeAreas', :git => 'https://github.com/DanyDeSan/PrivateShapeAreas.git'

  # Pods for RectangleArea

end
